[package]
name = "udptest"
version = "0.1.0"
authors = ["Quentin <Quentin Inkling>"]
edition = "2018"

[dependencies]
rusqlite = { version = "0.24", features = [ "bundled" ] }
log = "0.4"
env_logger = "0.8"
eframe = "0.10.0"

[dev-dependencies]
rand = "0.8"
